name: makadamia
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.10.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1 # Добавляем сюда зависимость

flutter_icons:
  android: true
  ios: true
  image_path: "images/makadamia.png" # Используем PNG вместо WEBP

flutter:
  uses-material-design: true
  assets:
    - images/makadamia.png
